# This workflow publishes conda package to a 
# conda channel under your own control
# Docs:
#   - https://github.com/maxibor/conda-package-publish-action
#   - https://github.com/conda-incubator/setup-miniconda
name: publish_conda

on:
  # Manually trigger workflow
  workflow_dispatch:
    inputs:
      release-tag:
        # The release tag input is not being used
        description: Release Tag (Optional)
        required: false
  # Trigger with new release
  release:
    types: [published]

jobs:
  conda-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup conda env
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        auto-update-conda: true
        python-version: 3.9
        conda-build-version: 3.21.7
        channels: conda-forge,bioconda
    - name: Bash
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: PowerShell Core
      shell: pwsh
      run: |
        conda info
        conda list
    - name: Set .condarc
      shell: bash -l {0}
      run: |
        # This is necessary to avoid package upload failure
        # with message: "anaconda_upload is not set"
        conda config --set anaconda_upload yes
        cat ~/.condarc
    - name: Publish-to-Conda
      uses: maxibor/conda-package-publish-action@v1.1
      with:
        # Example dummy anaconda token: ab-a1b2c30-0a22-3800-4732-034b4c7724ce
        subDir: 'conda-recipe'
        AnacondaToken: ${{ secrets.CONDA_API_TOKEN }}
      run: |
        # This is necessary to avoid package upload failure
        # with message: "anaconda_upload is not set"
        echo "SETTING CONDARC FOR ANACONDA UPLOAD"
        conda config --set anaconda_upload yes
        cat ~/.condarc